# Generated by Django 2.1.7 on 2019-03-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=25000),
            preserve_default=False,
        ),
    ]
